sudo: require
services: 
    - docker

before_install:
    - docker build -t jordanfrontdev/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true jordanfrontdev/docker-react npm run test
